blog/urls.py
from django.urls import path
from . import views
from .views import PostList
from .views import PostTemplate
from .views import PostListView
from .views import PostDetailView

app_name = 'blog'


urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path('', PostList.as_view(), name='post_list'),
    path('post/<int:pk>', views.post_detail, name='post_detail'),
    path('post/new', views.post_create, name='post_create'),
    path('post/<int:pk>/edit', views.post_edit, name='post_edit'),
    path('post/', views.post_edit_summer, name='post_edit_summer'),
    path('content/<int:pk>', views.summer_content, name='summer_content'),

    path('post_tem/', PostTemplate.as_view(), name='post_template'),
    path('post_list_view/', PostListView.as_view(), name='post_list_view'),
    path('post_detail_view/<int:pk>', PostDetailView.as_view(), name='post_detail_view'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# from django_summernote import models as summer_model
# from django_summernote import fields as summer_fields

# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True
        )

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absoulte_url(self):
        pass

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from blog.models import Post

# from django_summernote import fields as summer_fields


class PostForm(forms.ModelForm):

    title = forms.CharField(widget=forms.TextInput(
            attrs={
                'placeholder': 'Input Title',
            }
        ))

    text = forms.CharField(widget=forms.Textarea(
            attrs={
                'placeholder': 'Input Content',
            }
        ))

    class Meta:
        model = Post
        exclude = ('author', 'created_date', 'published_date', )

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if ('title' in title):
            return title
        else:
            raise forms.ValidationError('incorrect title')

    def clean_text(self):
        text = self.cleaned_data.get('text')
        if(text is not None):
            return text
        else:
            raise forms.ValidationError('incorrect text')


# class SummerForm(forms.ModelForm):
#     fields = summer_fields.SummernoteTextFormField()

#     class Meta:
#         model = SummerNote
#         fields = ('fields',)

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse

from blog.models import Post
from blog.forms import PostForm
from django.utils import timezone

from edit.forms import ArticleForm
from edit.models import Article

from django.views import View
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
# Create your views here.


# post list 를 published date 의 역순으로 정렬
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/blog_list.html', {'posts': posts})


class PostList(View):

    def get(self, request):
        posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
        return render(request, 'blog/blog_list.html', {'posts': posts})


class PostTemplate(TemplateView):
    template_name = 'blog/blog_list.html'

    def get_context_data(self, **kwargs):
        context = super(PostTemplate, self).get_context_data(**kwargs)
        posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
        context['posts'] = posts
        return context


class PostListView(ListView):

    model = Post
    template_name = 'blog/blog_list_view.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):

    model = Post
    template_name = 'blog/blog_detail_view.html'
    context_object_name = 'post'


# 글 내용
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    context = {
        'post': post
    }
    return render(request, 'blog/blog_detail.html', context)


# 글쓰기
def post_create(request):

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            newForm = Post.objects.create(
                    author=request.user,
                    title=form.cleaned_data['title'],
                    text=form.cleaned_data['text'],
                    published_date=timezone.now(),
                )
            newForm.save()

            # newForm = form.save(commit=False)
            # newForm.author = request.user
            # newForm.publish()
            # newForm.save()

            url = reverse('blog:post_detail', kwargs={'pk': newForm.pk})
            return redirect(url)
        else:
            print('form validation error')
            print(form.errors)

    else:
        form = PostForm()
        context = {
            'form': form,
        }
        return render(request, 'blog/blog_create.html', context)


# 글 수정
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            newForm = form.save(commit=False)
            newForm.publish()
            newForm.save()

            url = reverse('blog:post_detail', kwargs={'pk': newForm.pk})
            return redirect(url)

    else:
        form = PostForm(instance=post)
        context = {
            'form': form,
        }
        return render(request, 'blog/blog_edit.html', context)


# summernote test
def post_edit_summer(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            # print(form)
            form.save()
            return redirect(reverse('blog:post_list'))

    form = ArticleForm()
    ctx = {
        'form': form
    }
    return render(request, 'blog/blog_summer.html', ctx)


def summer_content(request, pk):
    article = get_object_or_404(Article, pk=pk)
    ctx = {
        'article': article
    }
    return render(request, 'blog/detail.html', ctx)

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>Djungo</title>
        <!--Facebook Bootstrap-->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">

        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
    </head>
    <body>
        <div class="page-header">

            <h1><a href="#">Djungo</a></h1>
        </div>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/blog_create.html
{% extends 'blog/base.html' %}

{% block content %}

<form action='' method='POST'>
  {% csrf_token %}

  {% for field in form  %}

    <div>
      <div style='vertical-align: top; display: inline-block;'>{{ field.label_tag }}</div>
      <div style='display: inline-block;'>{{ field }}</div>
    </div>
    <br/>
  {% endfor %}

  <button type='submit' class='btn btn-default'>등록</button>
</form>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}

{% block content %}

    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'blog:post_edit' post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <!-- Converts all newlines in a piece of plain text to HTML line breaks (<br>). -->
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

blog/templates/blog/blog_detail_view.html
{% extends 'blog/base.html' %}

{% block content %}

    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}

        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>

{% endblock %}

blog/templates/blog/blog_edit.html
{% extends 'blog/base.html' %}

{% block content %}

<form action='' method='POST'>
  {% csrf_token %}

  {% for field in form  %}
    <div>
      <div style='vertical-align: top; display: inline-block;'>{{ field.label_tag }}</div>
      <div style='display: inline-block;'>{{ field }}</div>
    </div>
    <br/>
  {% endfor %}

  <button type='submit' class='btn btn-default'>수정</button>
</form>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'blog:post_create' %}">글쓰기</a>
    {% endif %}

    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h1><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h1>
            <!-- <p>{{ post.text|linebreaksbr }}</p> -->
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/blog_list_view.html
{% extends 'blog/base.html' %}

{% block content %}

{% if posts %}
  <ul>
    {% for post in posts %}
      <li><a href="{% url 'blog:post_detail_view' post.pk %}">{{ post.title }}</a></li>
    {% endfor %}
  </ul>

{% else %}
  <p>No post</p>
{% endif %}

{% if is_paginated %}
<ul class='pagination'>

  {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo</a></li>
  {% else %}
    <li class="disabled"><span>&laquo;</span></li>
  {% endif %}


  {% for i in paginator.page_range %}

    {% if page_obj.number == i %}
      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}

  {% endfor %}


  {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&raquo</a></li>
  {% else %}
    <li class="disabled"><span>&raquo;</span></li>
  {% endif %}

</ul>
{% endif %}

{% endblock %}

blog/templates/blog/blog_summer.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>summernote test</title>
</head>

<body>
    <form action="/post/" method="post">
        {% csrf_token %}
        {{ form|safe }}
        <input type="submit" value="Submit" />
    </form>
</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}

<div id='titleDiv'>Title : {{ article.title }}</div>

<hr/>

<div id='contentDiv'>
</div>

<script>
    var a = '{{ article.content }}';
    console.log(a);
    document.getElementById('contentDiv').innerHTML = a.replace(/&lt;/gi, '<').replace(/&gt;/gi, '>').replace(/&quot;/gi, '"');
</script>

{% endblock %}