category/urls.py
from django.urls import path
from . import views

app_name = 'category'


urlpatterns = [
    path('list/', views.category_list, name='category_list'),

    path('<int:pk>/post/', views.post_create, name='post_create'),
    path('all/list/<int:theme_pk>/', views.AllList.as_view(), name='all_list'),
    path('buy/list/<int:theme_pk>/', views.BuyList.as_view(), name='buy_list'),
    path('sell/list/<int:theme_pk>/', views.SellList.as_view(), name='sell_list'),
    path('list/<int:pk>/', views.post_detail, name='post_detail'),
    path('apply/<int:pk>', views.apply_post, name='apply_post'),
    path('send/<int:post_pk>/<int:user_pk>', views.apply_send_mail, name='apply_send_mail'),
    path('check/<int:pk>', views.check_apply, name='check_apply'),
]

category/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Account
# Create your models here.

# 판매 게시판, 구매 게시판 따로 보여주는지, 아니면 카테고리 분류 후 다 보여주는지?


class MainTheme(models.Model):
    title = models.CharField(max_length=15)

    def __str__(self):
        return self.title


class MidTheme(models.Model):
    title = models.CharField(max_length=15)
    main_theme = models.ForeignKey(
            MainTheme,
            on_delete=models.CASCADE,
            related_name='related_mid_theme'
        )

    def __str__(self):
        return self.title


class SubTheme(models.Model):
    title = models.CharField(max_length=15)
    mid_theme = models.ForeignKey(
            MidTheme,
            on_delete=models.CASCADE,
            related_name='related_sub_theme'
        )

    def __str__(self):
        return self.title


# 남녀 카테고리(gender)
class Post(models.Model):

    POST_TYPE = (
        ('Buy', '구매글'),
        ('Sell', '판매글'),
    )

    POST_STATUS = (
            ('Deal', '거래중'),
            ('End', '거래완료'),
        )

    post_type = models.CharField(
            max_length=10,
            choices=POST_TYPE,
            default='Buy',
        )

    post_status = models.CharField(
            max_length=10,
            choices=POST_STATUS,
            default='Deal',
        )

    sub_theme = models.ForeignKey(
            SubTheme,
            on_delete=models.CASCADE,
            related_name='post_sub_theme',
            default=1,
        )
    author = models.ForeignKey(Account, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    thumbnail = models.ImageField(
            upload_to='thumbnail/%Y/%m/%d',
            default='static/img/default.jpg',
        )
    price = models.PositiveIntegerField()
    content = models.TextField()
    apply_user = models.ManyToManyField(
            User,
            related_name='applied_post',
            blank=True,
        )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return '{0} - {1}'.format(self.get_post_type_display(), self.title)


class Comment(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
            Post,
            on_delete=models.CASCADE,
            related_name='related_comment'
        )


# class SellPost(Post):

#     author = models.ForeignKey(Account, on_delete=models.CASCADE)
#     sub_theme = models.ForeignKey(
#             SubTheme,
#             on_delete=models.CASCADE,
#             related_name='sell_post_sub_theme'
#         )


# class PurchasePost(Post):

#     author = models.ForeignKey(Account, on_delete=models.CASCADE)
#     sub_theme = models.ForeignKey(
#             SubTheme,
#             on_delete=models.CASCADE,
#             related_name='purchase_post_sub_theme'
#         )

category/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from .models import Post
from .models import Comment


class PostForm(forms.ModelForm):

    content = forms.CharField(widget=SummernoteWidget(), label='')

    class Meta:
        model = Post
        exclude = ('author', 'post_status', 'created_at', 'updated_at', 'apply_user',)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ('author', 'created_at', 'post',)

category/views.py
from django.shortcuts import render, reverse, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.conf import settings

from django.views.generic.list import ListView

from .models import MainTheme
from .models import Post
from accounts.models import Account
from .forms import PostForm
from .forms import CommentForm
# Create your views here.


def category_list(request):
    main = get_object_or_404(MainTheme, pk=1)
    print(main)
    print(main.related_mid_theme.all())
    ctx = {
        'mainTheme': main,
    }
    return render(request, 'c_list.html', ctx)


class AllList(ListView):
    model = Post
    template_name = 'post_list.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        theme_pk = self.kwargs['theme_pk']
        post = Post.objects.filter(sub_theme__pk=theme_pk)
        return post


class BuyList(ListView):
    model = Post
    template_name = 'post_list.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        theme_pk = self.kwargs['theme_pk']
        return Post.objects.filter(sub_theme__pk=theme_pk).filter(post_type='Buy')


class SellList(ListView):
    model = Post
    template_name = 'post_list.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        theme_pk = self.kwargs['theme_pk']
        return Post.objects.filter(sub_theme__pk=theme_pk).filter(post_type='Sell')


@login_required
def post_detail(request, pk):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        if form.is_valid():
            saveForm = form.save(commit=False)
            saveForm.author = request.user
            saveForm.post = post
            saveForm.save()

            return redirect(reverse(
                    'category:post_detail',
                    kwargs={'pk': pk}
                ))

    ctx = {
        'post': post,
        'commentForm': form,
    }
    return render(request, 'post_detail.html', ctx)


@login_required
def post_create(request, pk):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            account = Account.objects.get(user_id=request.user.pk)
            saveForm = form.save(commit=False)
            saveForm.author = account
            if request.FILES:
                saveForm.thumbnail = request.FILES['thumbnail']
            saveForm.save()
            return redirect(reverse(
                    'category:all_list',
                    kwargs={'theme_pk': pk}
                ))

    form = PostForm(initial={'sub_theme': pk})
    ctx = {
        'form': form
    }
    return render(request, 'post_create.html', ctx)


@login_required
def apply_post(request, pk):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=pk)
        if post.apply_user.filter(pk=request.user.pk).exists():
            print('이미 신청')
            return redirect(reverse(
                    'category:post_detail',
                    kwargs={'pk': pk}
                ))
        else:
            post.apply_user.add(request.user)
            return redirect(reverse(
                    'category:post_detail',
                    kwargs={'pk': pk}
                ))


@login_required
def apply_send_mail(request, post_pk, user_pk):
    # post = get_object_or_404(Post, pk=post_pk)
    user = get_object_or_404(User, pk=user_pk)
    url = '{0}{1}'.format(
            'http://localhost:8000',
            reverse(
                    'category:check_apply',
                    kwargs={"pk": post_pk},
                )
        )
    html = '<a href="{0}">거래하기</a>'.format(url)
    send_mail(
            '거래 매치 메일',
            '',
            settings.EMAIL_HOST_USER,
            [user.email],
            html_message=html
        )

    return redirect(reverse(
            'accounts:profileView'
        ))


@login_required
def check_apply(request, pk):
    post = get_object_or_404(Post, pk=pk)

    ctx = {
        'post': post,
    }
    return render(request, 'check_apply.html', ctx)

category/templates/c_list.html
{% extends 'blog/base.html' %}
{% block content %}

    <div>
        <a href="{% url 'accounts:profileView' %}"><button class='btn btn-default'>profile</button></a>
    </div>
    {{ mainTheme }}
    <div>
        <ul>
            {% for theme in mainTheme.related_mid_theme.all %}
                <li>{{ theme.title }}</li>
                    <ul>
                        {% for sub_theme in theme.related_sub_theme.all %}
                            <a href="{% url 'category:all_list' sub_theme.pk %}"><li>{{ sub_theme.title }}</li></a>
                        {% endfor %}
                    </ul>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

category/templates/check_apply.html
{% extends 'blog/base.html' %}

{% block content %}

<div>
  ({{ post.get_post_status_display }}) - {{ post.title }}
</div>

<div>
  글쓴이와 연락하기
  <ul>
    <li>email: {{ post.author.email }}</li>
    <li>phone number: {{ post.author.phone }}</li>
  </ul>
</div>

{% endblock %}

category/templates/post_create.html
{% extends 'blog/base.html' %}

{% block content %}

<body>
  <div id='thumbnailImgDiv'>
    <img id='loadThumbnail' src=''/>
  </div>
    <form action="" method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form|safe }}
        <button type="submit">Post</button>
    </form>

    <script>
    /* 섬네일 미리보기 */

    function loadImg(value) {
      if(value.files && value.files[0]) {
        var fileReader = new FileReader();
        fileReader.onload = function(e) {
          $('#loadThumbnail').attr('src', e.target.result);
        }

        fileReader.readAsDataURL(value.files[0]);
      }
    }


    $('#id_thumbnail').on('change', function() {
      loadImg(this);

      document.getElementById('loadThumbnail').style.width = '300px';
      document.getElementById('loadThumbnail').style.height = '200px';
    });

    </script>
</body>

{% endblock %}

category/templates/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}

<div id='titleDiv'>Title : {{ post.title }}</div>

{% if post.apply_user.count %}
  <div>{{ post.get_post_status_display }}({{ post.apply_user.count }})</div>
{% else %}
  <div>{{ post.get_post_status_display }}</div>
{% endif %}

<hr/>
<div id='authorDiv'>author: {{ post.author }}</div>
<div id='postTypeDiv'>post type: {{ post.post_type }}</div>
<div id='subThemeDiv'>theme: {{ post.sub_theme.title }}</div>
<div id='priceDiv'>price: {{ post.price }}won</div>
<div id='dateDiv'>date: {{ post.created_at|date:'Y.n.d  a h:i' }}</div>
<hr/>

<div id='thumbnailDiv'>
  <img src='{{ post.thumbnail.url }}' style='width: 300px; height: 200px;'/>
</div>

<hr/>

<div id='contentDiv'>
</div>

<script>
    var a = '{{ post.content }}';
    console.log(a);
    document.getElementById('contentDiv').innerHTML = a.replace(/&lt;/gi, '<').replace(/&gt;/gi, '>').replace(/&quot;/gi, '"');
</script>

<div id='applyDiv'>
  <form action="{% url 'category:apply_post' post.pk %}" method='POST'>
    {% csrf_token %}
    <button type='submit'>거래 신청</button>
  </form>
</div>
<hr/>

<div id='commentFormDiv'>
  <form action='' method='POST'>
    {% csrf_token %}
    {{ commentForm.as_p }}
    <button type='submit'>댓글작성</button>
  </form>
</div>

<div id='commentsDiv'>
  {% if post.related_comment.count %}
    {% for comment in post.related_comment.all %}
      <div>
        <div style='display: inline-block;'>{{ comment.author }}</div> |
        <div style='display: inline-block;'>{{ comment.created_at|date:'Y.n.d  a h:i' }}</div>
        <div>{{ comment.content }}</div>
      </div>
      <hr/>
    {% endfor %}
  {% else %}
   <div>No comment</div>
  {% endif %}
</div>
{% endblock %}

category/templates/post_list.html
{% extends 'blog/base.html' %}

{% block content %}


{% if posts %}
  {% if user.is_authenticated %}
    <a class="btn btn-default" href="{% url 'category:post_create' posts.first.sub_theme.pk %}">글쓰기</a>
  {% else %}
    <p>로그인 후에 글쓰기가 가능합니다.</p>
  {% endif %}
{% else %}
  <a class="btn btn-default" href="{% url 'category:post_create' 1 %}">글쓰기</a>
{% endif %}

<div id='postTypeDiv'>
  {% if posts %}
    post type : {{ posts.first.get_post_type_display }}
    <p></p>
    <div>
      <a class="btn btn-default" href="{% url 'category:all_list' posts.first.sub_theme.pk %}">전체 게시글 보기</a>
      <a class="btn btn-default" href="{% url 'category:sell_list' posts.first.sub_theme.pk %}">판매 중인 게시글 보기</a>
      <a class="btn btn-default" href="{% url 'category:buy_list' posts.first.sub_theme.pk %}">구매 중인 게시글 보기</a>
    </div>
  {% else %}
    <p>작성된 게시글이 없습니다.</p>
  {% endif %}
</div>

<hr/>

{% if posts %}
  <ul>
    {% for post in posts %}
      <div style='display: inline-block; margin-right: 10px; margin-left: 10px;'>
        <div style='margin-bottom:20px;'>
          <a href="{% url 'category:post_detail' post.pk %}">
            <div><img src='{{ post.thumbnail.url }}' style='width: 150px; height: 100px;'/></div>
           <div>({{ post.get_post_type_display }}) {{ post.title }}</div>
         </a>
       </div>
      </div>
    {% endfor %}
  </ul>

{% else %}
  <p>작성된 게시글이 없습니다.</p>
{% endif %}

{% if is_paginated %}
<ul class='pagination'>

  {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo</a></li>
  {% else %}
    <li class="disabled"><span>&laquo;</span></li>
  {% endif %}


  {% for i in paginator.page_range %}

    {% if page_obj.number == i %}
      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}

  {% endfor %}


  {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&raquo</a></li>
  {% else %}
    <li class="disabled"><span>&raquo;</span></li>
  {% endif %}

</ul>
{% endif %}

{% endblock %}

category/templates/purchase_post.html
<div><h2>{{ purchase_post.title }}</h2></div>

<div>{{ purchase_post.content }}</div>

category/templates/sell_post.html
<div><h2>{{ sell_post.title }}</h2></div>

<div>{{ sell_post.content }}</div>